version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.11.2
    steps:
        - checkout
        - run: npm install
        - run:
            name: testrpc
            command: yarn blockchain
            background: true
        - run: yarn test
        - run: yarn coverage

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
